### ISSUE TITLE
Function polymorphism for cursor mapping props and context access

### ISSUE THREAD

**Issue by Yomguithereal** [Yomguithereal/baobab-react#12]
@bebraw, following up here.

What I mean is, if we consider the following component:

```js
var MyComponent = React.createClass({
  mixins: [mixin.branch],
  cursors: {
    name: function() {
      return ['step1', this.props.step2];
    }
  }
});
```

The function uses `this.props`.

Should we switch to something more like the following?

```js
var MyComponent = React.createClass({
  mixins: [mixin.branch],
  cursors: {
    name: function(props, context) {
      return ['step1', props.step2];
    }
  }
});
```

**Comment by bebraw** [comment]
I think the first option would be more consistent with the way how React works.

@christianalfoni, Any thoughts?

**Comment by christianalfoni** [comment]
Hi guys!

Actually, I think this adds unnecessary complexity, because:

```js
var MyComponent = React.createClass({
  mixins: [mixin.branch],
  cursors: function () {
    return {
      name: ['step1', this.props.step2]
    };
  }
});
```

.. does the same thing and is more flexible in scaling. Consider:

```js
var MyComponent = React.createClass({
  mixins: [mixin.branch],
  cursors: {
    name: function() {
      return ['step1', this.props.step2];
    },
   name2: function() {
      return ['step1', this.props.step2];
    },
  }
});
```

Would be:

```js
var MyComponent = React.createClass({
  mixins: [mixin.branch],
  cursors: function () {
    return {
      name: ['step1', this.props.step2],
      name2: ['step1', this.props.step2]
    };
  }
});
```
The signature on the example here is also consistant with `getInitialState`, `getDefaultProps` etc. Might even consider calling it: `getCursors`, to be even more consistant :-)

But yeah, in my opinion I think it would be a lot easier to to just have:

```js
cursors: function () {
  return {};
}
```
Gives all the flexibility you want and is most consistant with React.

**Comment by christianalfoni** [comment]
Hope I did not misunderstand completely what you were going for here :-)

**Comment by Yomguithereal** [comment]
@christianalfoni: both are currently possible :). Either `cursors` is a function or any of its keys. The question here was just to decide whether to rely on `this.props` or to explictly pass a `props` arg to the functions.

**Comment by christianalfoni** [comment]
Ah, I see :-)

Well, I think it is a bit overkill to provide both, especially because you would have to "unnaturally" bind/call these functions with the context of the component, or go totally out of the comfort zone and pass props as argument. It is also "another thing to learn". Sorry to be so negative, hehe, but when you have one way of doing things that covers all scenarios, but might require a bit more characters in some scenarios, I think it just makes the overall API less complex and easier to understand. Again, just my opinion ;-)
