### ISSUE TITLE
Recompute mappings on props update.

### ISSUE THREAD

**Issue by Yomguithereal** [Yomguithereal/baobab-react#16]

**Comment by Yomguithereal** [comment]
Related to Yomguithereal/baobab#176.

**Comment by Yomguithereal** [comment]
Cannot find a way to do so except in `componentDidUpdate` which does not seem like an ideal solution. Any idea @christianalfoni?

**Comment by christianalfoni** [comment]
Hi,

You also have `componentWillReceiveProps`. So that one only triggers on "external updates", `componentDidUpdate` runs also on "internal updates". Would that work?

**Comment by Yomguithereal** [comment]
Problem with those hooks is that `this.props` has not yet changed so the functions does not work. Related to #12  :).

**Comment by christianalfoni** [comment]
You receive new props as argument :-) 

```js
componentWillReceiveProps: function (newProps) {
  this.props // old props
  newProps // new props
}
```

**Comment by Yomguithereal** [comment]
Consider the following:

```js
var Component = React.createClass({
  mixins: function() {
    return {
      name: this.props.namePath
    }
  }
});
```

If I run this function during one of the hooks before `componentDidUpdate`, it won't work since `this.props` hasn't changed yet.

**Comment by christianalfoni** [comment]
Just to be sure, this one you are talking about?:

```js
  mixins: [mixin.branch],
  cursors: {
    name: function() {
      return ['step1', this.props.step2];
    },
   name2: function() {
      return ['step1', this.props.step2];
    },
  }
```

**Comment by christianalfoni** [comment]
And you want to update those cursors when the props change?

**Comment by christianalfoni** [comment]
Since those are not part of React and only being used by the mixin I would:

With silly code, but you get the point :-) :
```js
componentWillReceiveProps: function (nextProps) {
  var nameCursor = this.cursors.name.call({
    props: nextProps
  });
}
```

**Comment by Yomguithereal** [comment]
Yeah, I guess this is the only solution aside from passing props as an argument to the function itself. I'll probably hook on `componentWillUpdate` so this occurs after `shouldComponentUpdate` however.

**Comment by Yomguithereal** [comment]
Yeah I was speaking about:

```js
var Component = React.createClass({
  mixins: [branch.mixin],
  cursors: function() {
    return {
      name: this.props.namePath
    }
  }
});
```

I mistyped.

**Comment by christianalfoni** [comment]
Hm, yeah,

You can also:

```js
componentWillReceiveProps: function (nextProps) {
  setTimeout(function () {
    // Run those functions
  }, 0);
}
```
I would not consider that a hack, it is just running the cursors on the next tick

**Comment by Yomguithereal** [comment]
setTimeout is dangerous. What if the tree commits synchronously? The problem also with the .call on a simili component scope to override the props is that you make the user believe `this` is the scope of the component whereas it's really not.

**Comment by christianalfoni** [comment]
Normally I would agree on setTimeout, but after getting the cursors you still have to run setState which runs asynchronously. So instead of:

componentWillReceiveProps -> new props to new cursors -> setState - - - > render

would be:

componentWillReceiveProps - - - > new cursors -> setState - - - > render

So even if the tree commits synchronously it is still an async process to get the state to the component. I do not see where it could fail? Even it multiple sync triggers of componentWillReceiveProps occur it will still just grab the latest version of "this.props" when grabbing the new cursors?

**Comment by Yomguithereal** [comment]
Would your setTimeout solution render the component once or twice?

**Comment by christianalfoni** [comment]
First it renders because of the prop change (React Behaviour), then it renders again because of the mixin grabbing new cursors and setting to state (Baobab Behaviour). I do not quite see how it differs if the mixin is triggered synchronously or asynchronously as it will either way cause an extra render.

I do not think a sync setState() within componentWillReceiveProps changes the state for the next render. It will cause a completely new render after the one that is about to happen. 

Let me check that :-)

**Comment by christianalfoni** [comment]
You know, this.setState() in `componentWillReceiveProps` does not trigger a new render. I learned something new. Then I agree setTimeout is a bad idea, as it will cause an extra render :-)

**Comment by Yomguithereal** [comment]
So I guess the only possibility here is to:

1. Hook on `componentWillUpdate` so that we don't refresh cursors for nothing in case `shouldComponentUpdate` would return false.
2. Pass props and context to the function rather than executing in the component scope.

?

**Comment by christianalfoni** [comment]
Eyh, I got an idea:

```js
componentWillReceiveProps: function (nextProps) {
  var component = Object.create(this);  
  component.props = nextProps;
  this.cursors.call(component);
}

Now the component itself is just a prototype of a new object where you override with the next props. Now it runs in the context of the component with acces to everything as normal, except an instance property of the next props. This should work :-)

**Comment by Yomguithereal** [comment]
Still `this` would not be the component's scope and you are misleading the user, aren't you :)?

**Comment by christianalfoni** [comment]
Hehe, actually, it still is the components scope, it just acts like a delegate :-)

Using Object.create(this) has absolutely no effect at all, we only hook an extra object to the prototype chain. It technically runs in the "context" of a new object, but since the object is empty it will delegate absolutely everything to the original component. So calling any method etc. will just work. The only way to get in trouble is:

```js
cursors: function () {
  this.myNewProperty = 'foo';
  return {name: [this.props.name]}
},
componentWillReceiveProps: function () {
  var component = Object.create(this);  
  component.props = nextProps;
  var cursors = this.cursors.call(component);
}
```
It would be weird to do anything like that, but you could of course fix that too.

```js
cursors: function () {
  this.myNewProperty = 'foo';
  return {name: [this.props.name]}
},
componentWillReceiveProps: function () {
  var component = Object.create(this);  
  component.props = nextProps;
  var cursors = this.cursors.call(component);
  delete component.props;
  Object.keys(component).forEach(function (key) {
    this[key] = component[key];
  }, this);
}
```
Haha, yeah... it seems a bit crazy, but controlled crazy ;-)

**Comment by Yomguithereal** [comment]
In my experience this is a bad idea to make your user believe things which are untrue. Would it be so terrible to do the following?

```js
mixins: [mixins.branch],
cursors: function(props, context) {
  return {name: props.namePath};
}
```

**Comment by christianalfoni** [comment]
Anything else would require some sort of "hacking", so I think you are right in your assumption @Yomguithereal . It is the most clean solution :-)

**Comment by Yomguithereal** [comment]
I will let this settle down for 1-2 days to see whether there is something we would have missed. And if this does not solve by itself I will therefore apply this solution. Thanks for your input @christianalfoni :-).

**Comment by christianalfoni** [comment]
:+1:
