### ISSUE TITLE
dist-modules folder not exist after npm install. prebuild packge as part of the git?

### ISSUE THREAD

**Issue by asfktz** [Yomguithereal/baobab-react#27]
I get
Uncaught Error: Cannot find module "./dist-modules/mixins.js"
after npm install. need to "npm run prepublish" to make it work.
maybe pre building the package as part of the git repository would be helpful?

**Comment by Yomguithereal** [comment]
Hello @asfktz. @danawoodman has the same issue than you in #25. This is indeed because the prepublish hook is not run by npm when installing from git.

I used to store the built package in the git repository but I am always reluctant to do so for it make merging and other git operations painful at times.

I'll check whether I can hook the build somewhere else so that git install would work. Anyway, the package should be released very soon.

**Comment by Yomguithereal** [comment]
What I can do, however, before the package is published, is to keep the built files anyway.

**Comment by Yomguithereal** [comment]
I added the built files back for the time being.

**Comment by asfktz** [comment]
thank you, @Yomguithereal
