### ISSUE TITLE
Missing index.js?

### ISSUE THREAD

**Issue by christianalfoni** [Yomguithereal/baobab-react#30]
Hi there,

Just looking at the repo structure and would expect this to work:

```js
// Baobab is just required in the "index.js" of the project
import Baobab from 'baobab';
import BaobabReact from 'baobab-react';

BaobabReact.mixins
BaobabReact.decorators

import {root, branch} from 'baobab-react/mixins';
```

But there is no index.js file in dist-modules which package.json points to? And what is the difference between dist-modules and src folder? Just wondering :-) Might appear a pull request or two, want to do it right.

**Comment by Yomguithereal** [comment]
The package.json is indeed pointing toward a wrong file and I should fix this. Either the index.js should point toward a precise pattern either to a compilation of them. However, what I want to avoid is people unnecessarily loading all the code of this repo whereas they just want to use one of the pattern, hence the `require('baobab-react/pattern')` stuff.

`dist-modules` is where the built files are as opposed to `src` where the sources are. This is needed because half of the files are written in ES6/ES7.

So, for the time being, if you need to change some things you'll have to edit `src` then build with `npm run prepublish`.

**Comment by christianalfoni** [comment]
Hi @Yomguithereal ,

Aha I see. Not used to creating dist for transpilation reasons, but that makes perfect sense :-)

Yeah, I think it is a great idea to allow for pointing to a specific pattern, though `baobab-react` has to return something that makes sense. In my opinion that should be a an object with properties pointing to the different patterns. It would conform with other libraries too I think.

But yes, none of the examples I use in the article points directly to `baobab-react`, but just to avoid confusion I think it should return a directory :-)
