### ISSUE TITLE
How to define propTypes automatically

### ISSUE THREAD

**Issue by saulshanabrook** [Yomguithereal/baobab-react#64]
First off, thank you so much for this library :+1: 

I am using the decarator syntax and am trying to figure out if there is a way to automatically define the `propTypes`. Currently I am doing something like this:

```javascript
@branch({
  cursors: {
    live: ['live']
  }
})
class LiveList extends Component {
  render () {
    return (
      <div>
        <p className={styles.level}>
          We are currently at level {this.props.live.level}
        </p>
        <ol>
          {this.props.live.systems.map(function (system) {
            return <li><SystemItem {...system} /></li>
          })}
        </ol>
        <AddAddressOne />
      </div>
    )

  }
}

LiveList.propTypes = {
  live: React.PropTypes.shape({
      level: React.PropTypes.string,
      systems: React.PropTypes.arrayOf(React.PropTypes.shape({
        level: React.PropTypes.number,
        type: React.PropTypes.string
      }))
    })
}
```

As you can see, it's a bit painful to write the types for everything like that.

I am not sure if any prior thought has been given on this problem, but I think it would be nice if I could specify a type hierarchy for the whole tree, using react types, and then it would automatically set the propTypes on any element that is wrapped with a branch. 

Do you have any ideas/thoughts?

I would be happy to put in time implementing something, if we came up with a good solution.

**Comment by Yomguithereal** [comment]
Hello @saulshanabrook. This is indeed an interesting problem. The first issue I foresee right now is that since we use Higher order components, those actually manipulate the tree data through `state` before giving them as `props` to the composed component. And if I recall correctly, you cannot validate a component's state, just its props.

Another approach would be to validate the tree rather than the props passed through the tree. You can use the `validate` and `validationBehavior` settings of the tree to do so.

Just some quick ideas here.

**Comment by saulshanabrook** [comment]
Yeah. It seems like validating the tree makes the most sense. Do you have any insight into why react likes to know the types of all passed in `props`?

My linter tells me to fill them in, and React warns me if I don't, but do you know if there is a good reason to, if we are doing type linting elsewhere on the tree?

**Comment by Yomguithereal** [comment]
React wants you to fill PropTypes in so that what can be passed as props to your component is explicitly defined and so you can easily assess when you are giving invalid props to your components for debugging purposes. However, checking the PropTypes should be disabled in production because it is costly.

But I don't remember React warning you if you choose not to define a component's PropTypes.

The only use of both PropTypes + tree validation would be if you mean to reuse some components in other apps.

**Comment by saulshanabrook** [comment]
I thought I remembered a warning in the console when I didn't define propTypes, but I might be wrong.

So I guess using propTypes, with baobab, is another way of validating your tree. Instead of using the `validate` tree function, you could instead specify all the propTypes and that would serve as a form of validation for the tree's structure.

So what if this library had support to create a `validate` function for the tree, made out of React PropTypes, and then propagate that down to any of the Components that use parts of the tree as PropTypes automatically?
